#pragma once
#ifndef DEFINICIONES_H
#define DEFINICIONES_H

// Definiciones de constantes generales
constexpr int N_ANIMACIONES = 8;	// Total de animaciones de los personajes;
constexpr int MAX_IMG_POR_ANIM = 15;

// Definiciones de enumeraciones generales
enum class TipoAnimacion {
	// Movimientos
	IDLE,
	SALTO,
	SALTO_ATRAS,
	SALTO_ALANTE,
	AGACHE,
	ALANTE,
	ATRAS,

	// Ataques 
	// -- Puños
	PUNYO_FLOJO_ALANTE,
	PUNYO_MEDIO_ALANTE,
	PUNYO_FUERTE_ALANTE,

	PUNYO_FLOJO_PARADO,
	PUNYO_MEDIO_PARADO,
	PUNYO_FUERTE_PARADO,

	PUNYO_FLOJO_AGACHADO,
	PUNYO_MEDIO_AGACHADO,
	PUNYO_FUERTE_AGACHADO,
	
	// -- Patadas
	PATADA_FLOJO_ALANTE,
	PATADA_MEDIO_ALANTE,
	PATADA_FUERTE_ALANTE,

	PATADA_FLOJO_PARADO,
	PATADA_MEDIO_PARADO,
	PATADA_FUERTE_PARADO,

	PATADA_FLOJO_AGACHADO,
	PATADA_MEDIO_AGACHADO,
	PATADA_FUERTE_AGACHADO,

	// Herida
	HERIDA_AEREA,
	HERIDA_SUELO,
};

#endif